version: "3"
services:
  maxine-dev:
    # build: .
    image: beehivelab/maxine-dev:latest
    container_name: maxine-dev
    cap_add: 
      - SYS_PTRACE
    stdin_open: true
    tty: true
    environment:
      DISPLAY: unix${DISPLAY}
    ports:
      - "9873:873"
    volumes:
      - ~/.mx:/root/.mx # nocopy is important
      - $MAXINE_SRC:/root/maxine-src # nocopy is important
      - /tmp/.X11-unix:/tmp/.X11-unix
